[settings]
default_source_dir = "."
default_result_dir = ".verify-helper"

[language.cplusplus]
compile_options = ["-I/home/leal/beginner/atc/library"]

[config]
paths = ["verifier/**", "test/**"]

[document]
markdown = ".verify-helper/markdown"

[document-output]
copy_to = ["docs"]

[document.exclude]
paths = ["beg/**", "beg/*"]